### ISSUE TITLE
Template scattered on screen

### ISSUE THREAD

**Issue by tobitech** [BlackrockDigital/startbootstrap-shop-homepage#8]
What version of Bootstrap is the template compatible with, I'm using Bootstrap 3 in my project but the pages are scattered when I preview them in the browser.

**Comment by AbubakarWaryah** [comment]
i have same problem but you use same bootstrap.min.css which uses in this template mean.

**Comment by Jeff218869** [comment]
It was updated from ver 3.3 to 4.0.2 Beta which means the class-names are no longer in accordance if you're using 3.3 instead of the 3.3.
https://github.com/BlackrockDigital/startbootstrap-shop-homepage/blob/d60375c3ac5fc459ec7e30a126559d6dd0d26469/index.html
This is a link of the 3.3 version.

**Comment by davidtmiller** [comment]
This now uses Bootstrap 4 - you can go back in the releases or commit history to find Bootstrap 3 versions of this theme.
